#!/bin/bash


echo RNC/xml
for i in omcd3.rnc omcdsig3.rnc openmath3.rnc omcdgroup3.rnc
do
echo $i
perl rnc2dbk $i > ${i%%.rnc}rnc.xml
done


# openmath3.rnc has to be last
echo RNG
for i in omcd3.rnc omcdsig3.rnc  omcdgroup3.rnc openmath3.rnc
do
echo $i
java -jar trang.jar  $i ${i%%rnc}rng
done

# openmath3.rnc has to be last
echo XSD
for i in omcd3.rnc omcdsig3.rnc omcdgroup3.rnc  openmath3.rnc
do
echo $i
java -jar trang.jar  $i ${i%%rnc}xsd
done

>trang.txt
echo DTD
for i in openmath3.rnc
do
echo $i
sed -e "s/attvar =[^}]*}/attvar = OMATTR/" \
    -e "s/notom =.*$//" \
    -e "s/^.*element \*.*$//" \
    -e "s/ (omel|notom)\*/omel/" \
    -e "s/^.* text.$//" \
    -e "s/{pattern.*}}/}/" \
    -e "s/include .openmath3.rnc. {.*}/# OMDTD/" \
        $i >tmp.rnc

 java -jar trang.jar  tmp.rnc tmp.dtd 2>> trang.txt
 
 sed -e "s/OMFOREIGN .*>/OMFOREIGN ANY>/" \
     -e "s/:*ns1:*//g" \
     -e "s/\# OMDTD/<!ENTITY % omdtd SYSTEM \"openmath3.dtd\"> %omdtd;/"\
        tmp.dtd > ${i%%rnc}dtd
 sed -e "s/</\&lt;/g" ${i%%rnc}dtd > ${i%%.rnc}dtd.xml
done

for i in omcd3.rnc 
do
echo DTD
echo $i
sed -e  "s/| OMOBJ//" \
    -e "s/OMOBJ/text/" \
    -e "s/include .openmath3.rnc. {.*}/# OMDTD/" \
    -e "s/\(CDRevision[^,]*\)[)],/\\1)+,/" \
    -e "s/\(Description\)[)],/\\1)+,/" \
    -e "s/\(Role\)[?]/\\1/" \
    -e "s/ &/ |/g" \
        $i >tmp.rnc

 java -jar trang.jar  tmp.rnc tmp.dtd  2>> trang.txt
 

 sed -e "s/text-or-om \"(#PCDATA/text-or-om \"(#PCDATA|OMOBJ/" \
     -e "s/FMP (#PCDATA)/FMP (OMOBJ)/" \
     -e "s/:ns1//g" \
     -e "s/ns1://g" \
     -e "s/<!-- OMDTD -->/<!ENTITY % omdtd SYSTEM \"openmath3.dtd\"> %omdtd;/"\
        tmp.dtd > ${i%%rnc}dtd
 sed -e "s/</\&lt;/g" ${i%%rnc}dtd > ${i%%.rnc}dtd.xml


done

echo DTD
echo omcdgroup3.rnc
 java -jar trang.jar  omcdgroup3.rnc omcdgroup3.dtd 2>> trang.txt


for i in  omcdsig3.rnc
do
echo DTD
echo $i
sed -e  "s/| OMOBJ//" \
    -e "s/OMOBJ/text/" \
    -e "s/include .openmath3.rnc. {.*}/# OMDTD/" \
    -e "s/ &/ |/g" \
        $i >tmp.rnc

 java -jar trang.jar  tmp.rnc tmp.dtd  2>> trang.txt
 

 sed -e "s/Signature ..#PCDATA..../Signature (OMOBJ)/" \
     -e "s/CDSignatures .CDSComment./CDSignatures (CDSComment/" \
     -e "s/:ns1//g" \
     -e "s/ns1://g" \
     -e "s/<!-- OMDTD -->/<!ENTITY % omdtd SYSTEM \"openmath3.dtd\"> %omdtd;/"\
        tmp.dtd > ${i%%rnc}dtd
 sed -e "s/</\&lt;/g" ${i%%rnc}dtd > ${i%%.rnc}dtd.xml


done


echo validate
rxp -sxV omstd30.xml


echo html
saxon  -o omstd30html.xml omstd30.xml omstd30.xsl
echo chunked html
saxon   omstd30.xml omstd30.xsl chunk="true"
echo html-diff
saxon  -o omstd30html-diff.xml omstd30.xml omstd30.xsl showdiffs=true

echo tex
saxon  -o omstd30.tex omstd30.xml omstd30tex.xsl 
echo tex-diff
saxon  -o omstd30-diff.tex omstd30.xml omstd30tex.xsl showdiffs=true

echo pdf
pdflatex \\batchmode \\input omstd30.tex
if (grep -i rerun omstd30.log)
  then
  pdflatex \\batchmode \\input omstd30.tex
  if (grep -i rerun omstd30.log)
    then 
    pdflatex \\batchmode \\input omstd30.tex
    if (grep -i rerun omstd30.log)
      then
      pdflatex \\batchmode \\input omstd30.tex
    fi
  fi
fi

echo pdf-diff
pdflatex \\batchmode \\input omstd30-diff.tex
if (grep -i rerun omstd30-diff.log)
  then
  pdflatex \\batchmode \\input omstd30-diff.tex
  if (grep -i rerun omstd30-diff.log)
    then 
    pdflatex \\batchmode \\input omstd30-diff.tex
    if (grep -i rerun omstd30-diff.log)
      then
      pdflatex \\batchmode \\input omstd30-diff.tex
    fi
  fi
fi


echo zip
rm tmp.*
zip -q om30.zip o*.xml *.dtd [opv][me]*.xsl *.rnc *.rng *.xsd o*.pdf *.png *.ocd run docbook
